input {
  beats {
    port => 5044
  }
}

filter {
  if "ERROR" in [message] {
    mutate { add_field => { "severity" => "error" } }
  } else {
    mutate { add_field => { "severity" => "info" } }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logs-%{+YYYY.MM.dd}"
  }
}