version: '3'

services:

  app:
    build: ./app
    ports:
      - "5001:5000"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3002:3000"

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9101:9100"